### ISSUE TITLE
CMake fails to compile

### ISSUE THREAD

**Issue by moertle** [zeromq/zeromq4-x#54] opened 2014-01-30 22:42 UTC
When adding an external project to CMake:

    ExternalProject_Add(
        EP_zeromq
        PREFIX     ${CMAKE_CURRENT_BINARY_DIR}
        GIT_REPOSITORY https://github.com/zeromq/zeromq4-x.git
        GIT_TAG v4.0.3
        SOURCE_DIR ${CMAKE_CURRENT_BINARY_DIR}/src/zeromq

        CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=<INSTALL_DIR> -DZMQ_BUILD_FRAMEWORK=0
        )

The build fails with:

    [ 66%] Building CXX object CMakeFiles/test_connect_resolve.dir/tests/test_connect_resolve.cpp.o
    In file included from /code/build/thirdparty/src/zeromq/tests/test_connect_resolve.cpp:20:0:
    /code/build/thirdparty/src/zeromq/tests/testutil.hpp:25:31: fatal error: ../src/platform.hpp: No such file or directory
    compilation terminated.
    make[5]: *** [CMakeFiles/test_connect_resolve.dir/tests/test_connect_resolve.cpp.o] Error 1
    make[4]: *** [CMakeFiles/test_connect_resolve.dir/all] Error 2
    make[3]: *** [all] Error 2
    make[2]: *** [thirdparty/src/EP_zeromq-stamp/EP_zeromq-build] Error 2
    make[1]: *** [thirdparty/CMakeFiles/EP_zeromq.dir/all] Error 2
    make: *** [all] Error 2

**Comment by ronkorving** [comment] 2015-09-07 02:11
So this can be closed? :)

**Comment by jcfr** [comment] 2016-01-30 08:25
@moertle Using `master` (1206dc4 /2016-01-30), I confirm the problem is fixed.

```
$ cmake -version
cmake version 3.4.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).

$ cmake -DCMAKE_BUILD_TYPE=Release -DZMQ_BUILD_FRAMEWORK=0 ../ZeroMQ
[...]
-- Configuring done
-- Generating done
-- Build files have been written to: /path/to/ZeroMQ-Release

$ make -j5
[...]
[ 99%] Built target test_sub_forward
[ 99%] Built target test_system
[ 99%] Built target test_term_endpoint
[100%] Linking CXX executable bin/test_timeo
[100%] Built target test_timeo
```

@ronkorving @somdoron Please consider closing this issue.

**Comment by bluca** [comment] 2016-06-09 13:53
Thanks for verifying, closing

**Closed by bluca** 2016-06-09 13:53 UTC
